workflows:
    unit-testing:
        name: iOS Unit Tests
        max_build_duration: 120
        instance_type: mac_mini_m1



scripts:
  - name: Emulator tests
    script: |
      xcodebuild clean build test -project FeedLoader.xcodeproj -scheme FeedLoader CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO
